name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker-compose build

    - name: Start Docker Compose
      run: docker-compose up -d

    - name: Check running containers
      run: docker-compose ps -a

    - name: Stop Docker Compose
      if: always()
      run: docker-compose down
