name: CD_AIRFLOW

on:
    push: 
        branches: 
            - master
        paths: 
            - 'airflow/**'


jobs: 
    deploy_to_ec2:
        name: deploy_to_EC2
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout repo 
              uses: actions/checkout@v2

            - name: Deploy server
              uses: easingthemes/ssh-deploy@main
              with:
                SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                REMOTE_HOST: ${{ secrets.REMOTE_HOST_AIRFLOW }}
                REMOTE_USER: ${{ secrets.REMOTE_USER }}
                SOURCE: "/src/"
                TARGET: "/home/ubuntu/src"
                SCRIPT_AFTER: |
                    echo -e "AIRFLOW_UID=$(id -u)\nAIRFLOW_GID=0" > .env
                    sudo docker build -t apache-airflow:dbt-snowflake-dorian .
                    sudo docker compose up airflow-init
                    sudo docker compose up -d 